/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.github.ci.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        assertNotNull("app should have a greeting", "");
    }
}
